# Generated by Django 3.2.13 on 2022-09-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220928_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='deadling',
            new_name='deadline',
        ),
    ]
